apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: tomcat
  namespace: dev-envi-namespace
spec:
  selector:
    matchLabels: 
      app: tomcat
  template: 
      metadata: 
        name: mytomcat 
        labels: 
          app: tomcat
      spec:
        containers: 
          - name: tomcat
            image: mskoushik007/tomcat:1.0.1

