apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins
  namespace: dev-envi-namespace
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: jenkins
  strategy:
    type: RollingUpdate    
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template: 
    metadata:
      name: jenkins
      namespace: dev-envi-namespace
      labels:
        app: jenkins
    spec:
      volumes:
      - name: "jenkins-data"
        hostPath:
          path: "/root/jenkins"
      nodeSelector:
        size: large
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: "jenkins-data"
