apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: dev-envi-namespace
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: 0.4
    defaultRequest:
      memory: 500Mi
      cpu: 0.4
    type: Container

