apiVersion: v1
kind: Pod
metadata:
  name: tomcat-jenkins
  namespace: dev-envi-namespace
  labels:
    app: tomcat
spec:
  containers:
  - name: mytomcat
    image: prajwal1327/mytomcat:1.1.6
  - name: myenkins
    image: nginx:1.14.2

