apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: tomcat
spec:
  replicas: 0
  selector:
    matchLabels: 
      app: tomcat
  template: 
      metadata: 
        name: mytomcat 
        labels: 
          app: tomcat
      spec: 
        containers: 
          - name: tomcat
            image: ravindra45/ravindra45:1.1.1

